### ISSUE TITLE
Error during app generation

### ISSUE THREAD

**Issue by mrjazz** [Onix-Systems/nest-js-boilerplate#35]
During install I see the error:

```
394 verbose type range
395 verbose stack bson: No matching version found for bson@^4.6.2.
395 verbose stack     at module.exports (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/npm-pick-manifest/index.js:209:23)
395 verbose stack     at /Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:118:26
396 verbose cwd /Users/denis/Projects/node/todojazz
```

It's especially seems like a problem because I didn't install mongo driver

**Comment by VMihalov** [comment]
Thanks for the issue report. I could not reproduce this bug locally. Could you please write more information on how you caught this error. (npm version and generation steps)

**Comment by v-checha** [comment]
close, no activity.
