### ISSUE TITLE
Wrong path for packages.json

### ISSUE THREAD

**Issue by mrjazz** [Onix-Systems/nest-js-boilerplate#36]
During install generator stops with error below. Seems like a problem in wrong path, cause files was generated in /Users/denis/Projects/node/todojazz but in in dump I see path /Users/denis/Projects/node/package.json

```
node:events:368
      throw er; // Unhandled 'error' event
      ^

AssertionError [ERR_ASSERTION]: Trying to copy from a source that does not exist: /Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/generators/auth/templates/postgresql/oauth2/src/modules/
    at EditionInterface.exports.copy (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/mem-fs-editor/lib/actions/copy.js:49:3)
    at EditionInterface.module.exports [as copyTpl] (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/mem-fs-editor/lib/actions/copy-tpl.js:28:8)
    at AuthenticationGenerator.module.exports (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/generators/auth/steps/writing.js:27:11)
    at Object.<anonymous> (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/yeoman-generator/lib/index.js:991:25)
    at /Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/run-async/index.js:49:25
    at new Promise (<anonymous>)
    at /Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/run-async/index.js:26:19
    at runLoop.add.once.once (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/yeoman-generator/lib/index.js:992:11)
    at Immediate._onImmediate (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/yo/node_modules/grouped-queue/lib/subqueue.js:48:34)
    at processImmediate (node:internal/timers:464:21)
Emitted 'error' event on AuthenticationGenerator instance at:
    at Immediate.<anonymous> (/Users/denis/.nvm/versions/node/v16.13.0/lib/node_modules/generator-nest-js-boilerplate/node_modules/yeoman-generator/lib/index.js:1022:20)
    at processImmediate (node:internal/timers:464:21) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}
❯ npm start
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /Users/denis/Projects/node/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/Users/denis/Projects/node/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/denis/.npm/_logs/2022-05-12T21_15_06_152Z-debug.log
```

/Users/denis/Projects/node/package.json

**Comment by VMihalov** [comment]
Thanks for the issue report. The issue was fixed and a pull request was created with the changes.

**Comment by v-checha** [comment]
https://github.com/Onix-Systems/nest-js-boilerplate/pull/39
